# Generated by Django 5.1.4 on 2025-01-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('propertyType', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('area', models.FloatField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('contactname', models.CharField(max_length=255)),
                ('contactNumber', models.CharField(max_length=255)),
            ],
        ),
    ]
