# Generated by Django 5.1.4 on 2025-01-13 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proprty_Listing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advertisement',
        ),
    ]
