# Generated by Django 5.1.4 on 2025-01-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Proprty_Listing', '0002_delete_advertisement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('ad_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('propertyType', models.CharField(choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Land', 'Land'), ('Commercial', 'Commercial')], default='House', max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('contactName', models.CharField(blank=True, max_length=255, null=True)),
                ('contactNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
