# Generated by Django 5.1.2 on 2025-01-31 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proprty_Listing', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
